name: function

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      app-package-path:
        required: true
        type: string
        default: .
      environment:
        required: false
        type: string
        default: dev
      resource-group-name:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      CLIENT_SECRET:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_CREDENTIALS:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    outputs:
      output: ${{ steps.output.outputs.terraform }}
    environment: ${{ inputs.environment }}
    env:
      DOTNET_VERSION: '6.0.x'   
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          #creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ inputs.app-package-path }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Retrieve publish profile for deployment
        uses: Azure/cli@v1
        id: publishProfileRetrieval
        with:
          inlineScript: |
            publishProfiles=$(az webapp deployment list-publishing-profiles \
              --name "${{ inputs.app-name }}" \
              --resource-group "${{ inputs.resource-group-name }}" \
              --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}" --xml)
            echo "::add-mask::$publishProfiles"
            echo "::set-output name=publishProfiles::$publishProfiles"

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1.4.8
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: fa
        with:
          app-name: ${{ inputs.app-name }}
          package: '${{ inputs.app-package-path }}/output'
          publish-profile:  ${{ steps.publishProfileRetrieval.outputs.publishProfiles }}