name: function

on:
  workflow_call:
    inputs:
      resource-group-name:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: dev
    secrets:
      AZURE_CREDENTIALS:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  bicep:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    outputs:
      output: ${{ steps.output.outputs.terraform }}
    environment: ${{ inputs.environment }}
    #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Infrastructure
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ inputs.resource-group-name }}
          template: ./infrastructure/main.bicep