name: main

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  pull_request:

jobs:
  build-and-deploy-functions:
    permissions:
      id-token: write
      contents: read
    name: build-and-deploy-functions
    uses: ./.github/workflows/function.yml
    with:
      environment: dev
      resource-group-name: ServerlessOpenHackRG04-westeurope
      app-name: func-hack4-c2
      app-package-path: './ServerlessT4'
    secrets: inherit