name: main

on:
  push:
    branches:
      - "main"
      - "iac"
  workflow_dispatch:
  pull_request:

jobs:
  infrastructure:
    permissions:
      id-token: write
      contents: read
    name: infrastructure
    uses: ./.github/workflows/infrastructure.yml
    with:
      environment: dev
      resource-group-name: ServerlessOpenHackRG04-westeurope-iac
    secrets: inherit
  build-and-deploy-functions:
    needs: infrastructure
    permissions:
      id-token: write
      contents: read
    name: build-and-deploy-functions
    uses: ./.github/workflows/function.yml
    with:
      environment: dev
      resource-group-name: ServerlessOpenHackRG04-westeurope-iac
      app-name: func-hack4-sngvumm4ue4xo
      app-package-path: './ServerlessT4'
    secrets: inherit