name: main

on:
  push:
    branches:
      - "main"
      - "iac"
      - "iac-modules"
  workflow_dispatch:
  pull_request:

jobs:
  infrastructure:
    permissions:
      id-token: write
      contents: read
    name: infrastructure
    uses: ./.github/workflows/infrastructure.yml
    with:
      environment: dev
      resource-group-name: rg-h4
    secrets: inherit
  build-and-deploy-functions:
    needs: infrastructure
    permissions:
      id-token: write
      contents: read
    name: build-and-deploy-functions
    uses: ./.github/workflows/function.yml
    with:
      environment: dev
      resource-group-name: rg-h4
      app-name: func-h4api-2rupd4uf7ykeg
      app-package-path: './ServerlessT4'
    secrets: inherit